### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/text_to_speech#2]
@jlunenburg Which dependency did I forget to add today?

**Comment by Timple** [comment]
audio_something

Op 12 feb. 2017 12:33 a.m. schreef "Matthijs van der Burgh" <
notifications@github.com>:

**Comment by MatthijsBurgh** [comment]
I don't think sudo apt-get install audio_something is working.

**Comment by MatthijsBurgh** [comment]
@jlunenburg There is already an audio capture target. Should text_to_speech depend on it, or an other package?

**Comment by jlunenburg** [comment]
Dunno, guess it's started to record data using challenges. tue-robocup (or
whatever it is called) probably should depend on it. Otherwise: ask
@reinzor: he implemented data recording and cleaned up the targets

**Comment by reinzor** [comment]
this is synthesis, do you mean the `audio` target. Anyhow, fine to do this manually IMO
