### ISSUE TITLE
Soundboard file check is case sensative

### ISSUE THREAD

**Issue by MatthijsBurgh** [tue-robotics/text_to_speech#5]
I thinking the best solution is to have all file names lowercase and transform the possible path to lowercase.

**Comment by Timple** [comment]
Is this an issue? You need to look up the exact writing anyway since you probably will not write "My CPU is a neural-net processor... a learning computer.wav" correctly at once with the dash and points etc.

And it keeps the strings nicely readable

**Comment by MatthijsBurgh** [comment]
Yes, because now 'bring the action' does not work, but 'Bring the action does'. So if all the filenames are lowercase and in the TTS node you transform the incoming sentence, both example sentences will work.

**Comment by MatthijsBurgh** [comment]
So @Timple , what is our conclusion?

**Comment by Timple** [comment]
Looks like you did it anyway with this commit: a1f9c5384427853a1159742d73bb7caeba545fd5

**Comment by MatthijsBurgh** [comment]
I didn't know I already did it :p
